version: '3.9'
services:

  predixy:
    image: haandol/predixy:latest
    build:
      context: docker/predixy/
    container_name: predixy
    hostname: predixy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/predixy/conf:/etc/predixy/conf
      - ./predixy_data/logs:/etc/logs
    ports:
      - 7617:7617
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.8

  node1:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node1 
    hostname: node1 
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node1/data:/data
      - ./redis_data/node1/logs:/logs
    #network_mode: host
    ports:
      - 6381:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.11

  node2:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node2
    hostname: node2
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node2/data:/data
      - ./redis_data/node2/logs:/logs
    #network_mode: host
    ports:
      - 6382:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.12

  node3:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node3
    hostname: node3 
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node3/data:/data
      - ./redis_data/node3/logs:/logs
    #network_mode: host
    ports:
      - 6383:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.13

  node4:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node4
    hostname: node4 
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node4/data:/data
      - ./redis_data/node4/logs:/logs
    #network_mode: host
    ports:
      - 6384:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.14

  node5:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node5
    hostname: node5
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node5/data:/data
      - ./redis_data/node5/logs:/logs
    #network_mode: host
    ports:
      - 6385:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.15

  node6:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node6
    hostname: node6
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node6/data:/data
      - ./redis_data/node6/logs:/logs
    #network_mode: host
    ports:
      - 6386:6379
    networks: 
      redis-net: 
        ipv4_address: 172.24.0.16

  node7:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node7
    hostname: node7
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node7/data:/data
      - ./redis_data/node7/logs:/logs
    #network_mode: host
    ports:
      - 6387:6379
    networks:
      redis-net:
        ipv4_address: 172.24.0.17

  node8:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node8
    hostname: node8
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node8/data:/data
      - ./redis_data/node8/logs:/logs
    #network_mode: host
    ports:
      - 6388:6379
    networks:
      redis-net:
        ipv4_address: 172.24.0.18

  node9:
    image: redis:6.2.4
    restart: unless-stopped
    container_name: node9
    hostname: node9
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis_data/node9/data:/data
      - ./redis_data/node9/logs:/logs
    #network_mode: host
    ports:
      - 6389:6379
    networks:
      redis-net:
        ipv4_address: 172.24.0.19

  redis-cluster:
    image: redis:6.2.4
    #restart: unless-stopped
    container_name: redis-cluster
    hostname: redis-cluster
    command: redis-cli --cluster create 172.24.0.11:6379 172.24.0.12:6379 172.24.0.13:6379 172.24.0.14:6379 172.24.0.15:6379 172.24.0.16:6379 172.24.0.17:6379 172.24.0.18:6379 172.24.0.19:6379 --cluster-replicas 2 --cluster-yes
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #network_mode: host
    ports:
      - 6379:6379
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9
    networks:
      redis-net:
        ipv4_address: 172.24.0.20

#docker network create --gateway 172.24.0.1 --subnet 172.24.0.0/16 redis-net
networks:
  redis-net:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
